Repository mattermost/mattermost-plugin-zoom, pull requests merged in 2020-03, with the labels that each got.

#75 MM-22921 - Updating zoom styling for attachment
  webapp/src/components/post_type_zoom/post_type_zoom.jsx
Labels: 2: Dev Review

#73 [MM-22638] Fix undefined name
  server/command.go
  server/http.go
  webapp/src/components/post_type_zoom/index.js
Labels: 3: Reviews Complete, QA Review Done

#87 Update Dependencies
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete

#90 go mod tidy
  go.sum
Labels: 3: Reviews Complete

#88 [GH-86] Update client OnConfigurationChange
  server/configuration.go
Labels: 3: Reviews Complete, QA Review Done
