Repository mattermost/mattermost-plugin-zoom, pull requests merged in 2020-06, with the labels that each got.

#116 Adding slack attachment on messages without plugin (and mobile)
  server/http.go
Labels: 4: Reviews Complete

#124 Bump go dependencies and go mod tidy
  go.mod
  go.sum
Labels: 4: Reviews Complete

#115 Integrate GolangCI-Lint
  .golangci.yml
  Makefile
  build/custom.mk
  build/deploy/main.go
  build/manifest/main.go
  build/setup.mk
  go.mod
  go.sum
  server/command.go
  server/configuration.go
  server/http.go
  server/manifest.go
  server/plugin.go
  server/plugin_test.go
  server/utils.go
  server/zoom/client.go
Labels: 4: Reviews Complete

#126 Remove usage and setup from readme and link to GitBook
  README.md
Labels: 4: Reviews Complete

#122 Bump dependency audit fix
  build/manifest/main.go
  server/manifest.go
  webapp/.eslintrc.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/index.js
  webapp/src/manifest.js
Labels: 2: Dev Review

#125 [GH-121] Add info to Zoom OAuth UI
  plugin.json
Labels: 1: PM Review, QA Review Done

#130 Add .npmrc file for save-exact packages
  webapp/.npmrc
Labels: 4: Reviews Complete

#135 Update .circleci/config.yml
  .circleci/config.yml
Labels: 4: Reviews Complete

#133 [GH-127] Remove Disconnect command when using JWT
  server/command.go
Labels: 4: Reviews Complete

#138 [GH-137] Fix "If user's email is not valid for JWT Zoom, launching Zoom from the icon will show oAuth link "
  server/http.go
Labels: 2: Dev Review

#134 Store post ID when creating meeting via slash command, add some logging and set expiry time to meeting post IDs to avoid garbage in the KVStore
  server/command.go
  server/http.go
  server/plugin.go
  server/plugin_test.go
Labels: QA Review Done

#123 Bump version to 1.4.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete
