Repository mattermost/mattermost-plugin-zoom, pull requests merged in 2020-10, with the labels that each got.

#165 Add autocomplete icon
  go.mod
  go.sum
  server/command.go
  server/configuration.go
  server/plugin.go
Labels: 4: Reviews Complete

#162 Update webhook-configuration.md (#159)
  docs/installation/zoom-configuration/webhook-configuration.md
Labels: 4: Reviews Complete

#158 Update README.md
  docs/installation/mattermost-setup.md
  docs/installation/zoom-configuration/README.md
  docs/installation/zoom-configuration/zoom-setup-jwt.md
  docs/installation/zoom-configuration/zoom-setup-oauth.md
  docs/usage/connect-your-account.md
  docs/usage/start-meetings.md
Labels: 4: Reviews Complete

#169 GH-168: call strings.ReplaceAll instead of strings.Replace
  server/command.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#150 [GH-136] Refactor zoom OAuth to use the client model
  server/cipher.go
  server/command.go
  server/configuration.go
  server/http.go
  server/plugin.go
  server/store.go
  server/zoom/client.go
  server/zoom/compliance.go
  server/zoom/jwt.go
  server/zoom/meeting.go
  server/zoom/oauth.go
  server/zoom/user.go
Labels: 3: QA Review

#132 Add OAuth with account level app
  plugin.json
  server/command.go
  server/configuration.go
  server/http.go
  server/plugin.go
  server/store.go
  server/zoom/client.go
  server/zoom/jwt.go
  server/zoom/oauth.go
Labels: 4: Reviews Complete
