Repository mattermost/mattermost-plugin-zoom, pull requests merged in 2023-10, with the labels that each got.

#310 [GH-309]: Removed mention of JWT setup from the README as it is no longer supported.
  README.md
Labels: Hacktoberfest

#284 GH-154: Created the settings command to change the preferences for meeting creation
  server/command.go
  server/http.go
  server/plugin_test.go
  server/store.go
  server/telemetry.go
  server/webhook_test.go
  webapp/src/actions/index.js
  webapp/src/client/client.js
  webapp/src/components/post_type_zoom/post_type_zoom.jsx
  webapp/src/constants/svgs.js
Labels: Lifecycle/1:stale, 3: QA Review

#299 [GH-283]: Fixed issue #283 'Removed the code for depreciated JWT'
  README.md
  go.mod
  go.sum
  plugin.json
  server/command.go
  server/configuration.go
  server/plugin.go
  server/plugin_test.go
  server/telemetry.go
  server/webhook_test.go
  server/zoom/jwt.go
  server/zoom/oauth.go
Labels: 4: Reviews Complete

#308 [GH-152]: Updated instruction of adding scope to Oauth App
  README.md
  assets/scopes-account-level-app.png
  assets/scopes-user-level-app.png
  assets/scopes.png
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#307 [GH-300]: Fixed the JS error while posting meeting link to thread view
  server/http.go
  webapp/src/actions/index.js
  webapp/src/client/client.js
  webapp/src/index.js
Labels: 3: QA Review

#287 [GH-240]:Fixed issue #240 edited the pretext of custom post
  webapp/src/components/post_type_zoom/post_type_zoom.jsx
Labels: 4: Reviews Complete
